_skip_if_exists:
  - LICENSE
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - .gitignore
  - CITATION.CFF

# default values
defaults:
  software_name: Awesome
  # software_purpose: "The purpose of {{ software_name }} is ..."
  # owner: "Iowner"

