project:
  type: book

book:
  title: "Templates for Research Software"
  author: "Manuel Garcia, Angelina Momin"
  date: "2/17/2025"
  chapters:
    - index.qmd
    - part: "TEMPLATES"
      chapters:
        - meta-template.qmd
        - project-template.qmd
    - part: "USE CASES"
      chapters:
        - python-case.qmd
        - notebook-case.qmd
        - r-case.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

